### ISSUE TITLE
Schema to-do list

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#24]
**Everything schema**

- [x] Cut schema to manageable size

- [ ] Build process to merge schema pieces

- [ ] Add attributes related to documentation

- [ ] Add attributes related to ASF

- [x] Create inital documentation 

- [ ] Update doc

- [ ] Create process to update the schema when needed

**Comment by ChrisLatRNCan** [comment]
Status

[fgpa-schema-splitter](https://github.com/ChrisLatRNCan/fgpa-schema-splitter) as been created to load, append and cut in pieces the schema (to be consumed by the [Author](https://github.com/fgpv-vpgf/fgpa-apgf)). It also manages internationalization through a csv file.

**Comment by yblain** [comment]
this list is not valid anymore
